[build]
  command = "bash netlify-build.sh"
  publish = "build/web"

[build.environment]
  FLUTTER_VERSION = "3.29.2"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"

[[headers]]
  for = "/flutter_service_worker.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
